=== api-evangelist/amazon-iot-twinmaker/json-schema/iot-twinmaker-property-definition-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-iot-twinmaker/refs/heads/main/json-schema/iot-twinmaker-property-definition-response-schema.json",
  "title": "PropertyDefinitionResponse",
  "description": "An object that contains response data from a property definition request.",
  "type": "object",
  "properties": {
    "dataType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DataType"
        },
        {
          "description": "An object that contains information about the data type."
        }
      ]
    },
    "isTimeSeries": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "A Boolean value that specifies whether the property consists of time series data."
        }
      ]
    },
    "isRequiredInEntity": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "A Boolean value that specifies whether the property is required in an entity."
        }
      ]
    },
    "isExternalId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "A Boolean value that specifies whether the property ID comes from an external data store."
        }
      ]
    },
    "isStoredExternally": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "A Boolean value that specifies whether the property is stored externally."
        }
      ]
    },
    "isImported": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "A Boolean value that specifies whether the property definition is imported from an external data store."
        }
      ]
    },
    "isFinal": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "A Boolean value that specifies whether the property definition can be updated."
        }
      ]
    },
    "isInherited": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "A Boolean value that specifies whether the property definition is inherited from a parent entity."
        }
      ]
    },
    "defaultValue": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DataValue"
        },
        {
          "description": "An object that contains the default value."
        }
      ]
    },
    "configuration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Configuration"
        },
        {
          "description": "A mapping that specifies configuration information about the property."
        }
      ]
    },
    "displayName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PropertyDisplayName"
        },
        {
          "description": "A friendly name for the property."
        }
      ]
    }
  },
  "required": [
    "dataType",
    "isTimeSeries",
    "isRequiredInEntity",
    "isExternalId",
    "isStoredExternally",
    "isImported",
    "isFinal",
    "isInherited"
  ]
}

=== api-evangelist/amazon-iot-twinmaker/examples/iot-twinmaker-property-definition-response-example.json
{
  "dataType": "example-value",
  "isTimeSeries": "2025-03-15T14:30:00Z",
  "isRequiredInEntity": "example-value",
  "isExternalId": "id-abc123",
  "isStoredExternally": "example-value",
  "isImported": "example-value",
  "isFinal": "example-value",
  "isInherited": "example-value",
  "defaultValue": "example-value",
  "configuration": "example-value",
  "displayName": "example-resource"
}
